---
driver:
  name: digitalocean

driver_config:
  private_networking: false
  region: nyc3

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14-04-x64
  - name: ubuntu-12-04-x64

suites:
  - name: base
    run_list:
      - role[base]
    attributes:
